---
repos:
  # Do not allow direct push to main/master branches
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: no-commit-to-branch

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.32.0
    hooks:
      - id: yamllint
        args: [--strict]

  - repo: https://github.com/Mateusz-Grzelinski/actionlint-py
    rev: v1.6.26.11
    hooks:
      - id: actionlint

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.10.0
    hooks:
      - id: black
        # It is recommended to specify the latest version of Python
        # supported by your project here, or alternatively use
        # pre-commit's default_language_version, see
        # https://pre-commit.com/#top_level-default_language_version
        language_version: python3.11

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.52.0'
    hooks:
      - id: eslint
        files: \^*.toml
        types: [file]
        additional_dependencies:
          - eslint
          - eslint-config-google
          - eslint-loader
          - eslint-plugin-react
          - babel-eslint

  - repo: https://github.com/pycqa/flake8
    rev: '6.1.0'
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.6.1'
    hooks:
      - id: mypy
