---
name: "⛔️ Standalone linting checks"

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - "*"
      - "!update-devops-tooling"

jobs:
  linting:
    # Don't run when pull request is merged
    if: github.event.pull_request.merged == false
    name: "Unsupported by pre-commit.ci"
    runs-on: "ubuntu-latest"

    steps:

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Install linting tools"
        run: pip install pre-commit mypy

      # - name: "Install dependencies"
        # yamllint disable rule:line-length
      #   run: |
      #     SOURCE=".pre-commit-config.yaml"
      #     echo "Install Python dependencies from: $SOURCE"
      #     echo "With: pip install -y$PKGS"
      #     # yamllint disable-line rule:line-length
      #     PKGS=$(yq '.repos[] | select (.repo == "https://github.com/pre-commit/mirrors-mypy")' .pre-commit-config.yaml | \
      #      grep additional_dependencies | \
      #      awk -F: '{print $2}' | \
      #      sed "s/\[//g" | \
      #      sed "s/\]//g" | \
      #      sed "s/,//g" | \
      #      sed 's/"//g')

      - name: "Run mypy from pre-commit"
        run: pre-commit run mypy -a
